# Generated by Django 5.2.6 on 2025-10-01 03:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
                ('notice_type', models.CharField(choices=[('Common', 'Common'), ('Examinations', 'Examinations'), ('Assignments', 'Assignments'), ('Notes', 'Notes'), ('Events', 'Events'), ('Backs', 'Backs'), ('Urgent', 'Urgent')], default='Common', max_length=50)),
                ('department', models.CharField(choices=[('CSE', 'Computer Science and Engineering'), ('EE', 'Electrical Engineering'), ('ME', 'Mechanical Engineering'), ('CE', 'Civil Engineering')], default='CSE', max_length=50)),
                ('semester', models.CharField(choices=[('S1', 'Semester 1'), ('S2', 'Semester 2'), ('S3', 'Semester 3'), ('S4', 'Semester 4'), ('S5', 'Semester 5'), ('S6', 'Semester 6'), ('S7', 'Semester 7'), ('S8', 'Semester 8'), ('ALL', 'All Semesters')], default='ALL', max_length=50)),
                ('description', models.TextField()),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-posted_on'],
            },
        ),
    ]
