# Generated by Django 5.2.6 on 2025-10-01 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notice',
            options={'ordering': ['-posted_at']},
        ),
        migrations.RenameField(
            model_name='notice',
            old_name='posted_on',
            new_name='posted_at',
        ),
    ]
