# Generated by Django 5.2.6 on 2025-10-02 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0004_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='attachment',
        ),
    ]
